dist: xenial
language: python
python:
- 3.7
- 3.6
install:
- pip install -U tox-travis
- python setup.py -q install
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: johancarlin
  password:
    secure: azP5qPDJ9KhFUt1hFRS2GrdPT+97KYNfC6J2hsmuZhPpPECCLt3aWn3Dq67E5Vc09RZU7f7XgXtIuInn2ouRchg2CHfsGcAsFc1pa9lE8m0+ra2uX9Z+rkA74qyugQT1ZCmS4bkRxzvMLllQAyrmGVfMh3b/Xp5lWddEqOES6rZxfZcLbzrJELrMg/fKAR7yTkkyI0WZY/sqVqaap/BQVbkuRQhSbcb9vyYl0Jo8mBd4Lma2cRjcONQbx5L7troNFxmpk0zfK+wWWcfW8ltLYHbbdGnxSDMVlBVTNuj2hfR/jHCVdgZniSce6Tnu2nY4RWR1J/N0XG+9Bngl7sZVP/irCP3EMF3D+Ekcs7pzzC7EPy0xG5EJm6wGaKMggzhwctzyHjpg6R7HQWWD7WMq+vdncv4AFLwvvmXq28ECKINSfizeoanNAi7DHFT0hqN9DeJZwwQgH46Y74wZmkCFvfT/ZaqRtKg7jVi+cxl2OeJy3BpH8KHMtQULc2xrkIAlEgOnucZlrMZZGPuPYTuaM7XWWxkFW3xWllbtr8wXcjRmWhH0xvUYrnD+ekuOVB2/jx4S4Sz6sfM+fQeRbvEj3gVOl0kxTPUopkn98HU4IDGHZ7okhREu7LFyYzsH18vFZumKER8t5B/3j+o7/Y0Lu0H9FHEV0444G//6NsMPEvo=
  on:
    tags: true
    repo: jooh/bindit
    python: 3.7
services: docker
before_install: docker pull alpine:latest
